### ISSUE TITLE
send read side ID (projection name) in read side request

### ISSUE THREAD

**Issue by zenyui** [namely/chief-of-state#198]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
It would be nice to have access to the read side ID (`projection_name`) inside the read side request proto. for context, a current team is considering reusing the same image/container to serve many read sides with separate offsets. while this might not be a great design for all use cases, IMO makes sense to have access to the read side ID.

@Tochemey we had originally given access via headers to some other read side details (sequence number, tag, etc), so perhaps we could move these into the request proto.

**Describe alternatives you've considered**
send as a header

**Additional context**
n/a

**Comment by Tochemey** [comment]
The read side ID is the identifier of an actor within the cluster. We can circle back on this. I just want to let all of us know that the ID is like the actor persistent ID.

**Comment by zenyui** [comment]
@Tochemey I was referring to the `projection_name`
