### ISSUE TITLE
Investigate and fix connection pool issue when db connection is closed

### ISSUE THREAD

**Issue by Tochemey** [namely/chief-of-state#394]
**Describe the bug**
Failed to validate connection org.postgresql.jdbc.PgConnection@7f8d9791 (This connection has been closed.). Possibly consider using a shorter maxLifetime value.

**To Reproduce**
  1. Start COS based application
  2. Shutdown the database and wait for while
  3. Restart COS (need to revalidate this step)
  3. Observe the log

**Expected behavior**
TBD

**Screenshots**
```
Connection org.postgresql.jdbc.PgConnection@504ff561 marked as broken because of SQLSTATE(57P01), ErrorCode(0)
cos-readside-pool - Failed to validate connection org.postgresql.jdbc.PgConnection@7f8d9791 (This connection has been closed.). Possibly consider using a shorter maxLifetime value
```

**Additional context**

**Comment by 12ashokparmar** [comment]
May be useful.
spring.datasource.hikari.leakDetectionThreshold=2000
logging.level.com.zaxxer.hikari=DEBUG
spring.datasource.hikari.max-lifetime=600000
spring.datasource.testWhileIdle=true
spring.datasource.test-on-borrow=true
