### ISSUE TITLE
configurable retries for write-side gRPC calls

### ISSUE THREAD

**Issue by zenyui** [namely/chief-of-state#68]
**Is your feature request related to a problem? Please describe.**
configuration for retry behavior on the write-side gRPC calls

**Describe the solution you'd like**
- a config/env var to set the number of retries with some reasonable default.
- perhaps an exponential backoff?
- perhaps it should not retry on validation errors?

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by zenyui** [comment]
I'd like to cancel this for now.

**Comment by Tochemey** [comment]
We can reopen the issue. However a kind of configuration can be provided to have some exponential backoff mechanisms for command and event handler in case the error is solely due to network problem and not application related.
